Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.hostname = 'debrief-dev-box'

  config.vm.network :private_network, ip: "192.168.50.4"
  config.ssh.forward_agent = true

  config.vm.synced_folder "../../debrief", "/debrief", nfs: true

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
  end
end